apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.ports.openwire }}
      name: openwire
    - port: {{ .Values.service.ports.web }}
      name: web
  selector:
    app: {{ include "activemq.fullname" . }}
  type: {{ .Values.service.type }}
