apiVersion: v1
kind: Pod
metadata:
  name: activemq-producer
  namespace: activemq
spec:
  restartPolicy: Never
  serviceAccountName: activemq-sa
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: producer
      image: apache/activemq-classic:5.19.0
      env:
        - name: ACTIVEMQ_USERNAME
          value: "admin"
        - name: ACTIVEMQ_PASSWORD 
          value: "admin"
        - name: ACTIVEMQ_BROKER_URI
          value: "tcp://activemq.activemq.svc.cluster.local:61616"
        - name: ACTIVEMQ_QUEUE
          value: "queue://test.queue" 
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "=== Sending test messages ===" 
            /opt/apache-activemq/bin/activemq producer --user $ACTIVEMQ_USERNAME \
              --password $ACTIVEMQ_PASSWORD --destination $ACTIVEMQ_QUEUE "Message_$i" --brokerUrl $ACTIVEMQ_BROKER_URI 
          echo "=== Producer Done ==="
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault